void draw_pixelBall();
void draw_greenTile();
void draw_blueTile();
void draw_yellowTile();
void draw_redTile();
void draw_paddle(int x, int y);
void draw_background();
void collision_tile();
void del_tile(int x, int y);
void eraseSprite(int x, int y, int spr_width, int spr_height);
void drawSprite(int x, int y);
void move_paddle(char* str, int barX);
void welcomeGame();
void draw_greyBrick(int x, int y);
char displayDec(int num, int x, int y);
void draw_gameOver();
void winGame(int score);
void clear_screen();